/********************************************************
 * Created by: CloudRoute @ CloudRoute Solutions
 * Created Date: 19/03/20.
 * Description: JoinNowIndividualRequestWrapper
 ********************************************************/

public class JoinNowIndividualRequestWrapper {

    public String pm_primary_con_street;
    public String pm_primary_con_city;
    public String pm_primary_con_state;
    public String pm_primary_con_country;
    public String pm_primary_con_postalCode;

    public String pm_project;
    public String pm_product_detail;
    public Decimal pm_fees;

    public String pm_primary_con_id;
    public String pm_primary_con_fname;
    public String pm_primary_con_lname;
    public String pm_primary_con_title;
    public String pm_primary_con_emailParam;
    public String pm_primary_con_phone;
    public String pm_primary_con_twitter;
    public String pm_primary_con_github;
    public String pm_primary_con_linkedIn;
    public String category;

}